# Results{-}  


## Assembly{-}   


### Stats{-}  


  Scaffolds = 694  
  Contigs = 694  
  Scaffold Length = 1,216,826,970  
  Contig Length = 1,216,826,970  
  Contig N50 = 28,813,006  
  Contig L50 = 17  
  Scaffold N50 = 28,813,006  
  Scaffold L50 = 17  
  Max scaffold size = 50,275,871  
  Min scaffold size = 14,196  

#### C. variegatus{-}  

  Scaffolds = 1,139  
  Contigs = 1,139  
  Contig Length = 1,272,562,944  
  Scaffold Length = 1,272,562,944  
  Contig N50 = 26,363,765  
  Contig L50 = 17  
  Scaffold N50 = 26,363,765  
  Scaffold L50 = 17  
  Max scaffold size = 79,807,540  
  Min scaffold size = 10,992  

#### C. desquamator{-}  

  Scaffolds = 694  
  Contigs = 694  
  Scaffold Length = 1,216,826,970  
  Contig Length = 1,216,826,970  
  Contig N50 = 28,813,006  
  Contig L50 = 17  
  Scaffold N50 = 28,813,006  
  Scaffold L50 = 17  
  Max scaffold size = 50,275,871  
  Min scaffold size = 14,196  

#### C. brontotheroides{-}  

  Scaffolds = 1,121  
  Contigs = 1,121  
  Scaffold Length = 1,263,524,688  
  Contig Length = 1,263,524,688  
  Contig N50 = 27,861,740  
  Contig L50 = 17  
  Scaffold N50 = 27,861,740  
  Scaffold L50 = 17  
  Max scaffold size = 47,301,365  
  Min scaffold size = 12,425    


### Busco (Benchmarking Universal Single-Copy Orthologue)  

  C:99.3%[S:97.7%,D:1.6%],F:0.5%,M:0.2%,n:954  
	947	Complete BUSCOs (C)  
	932	Complete and single-copy BUSCOs (S)  
	15	Complete and duplicated BUSCOs (D)  
	5	Fragmented BUSCOs (F)  
	2	Missing BUSCOs (M)  
	954	Total BUSCO groups searched  

#### C. variegatus  

	C:99.1% [S:96.6%,D:2.5%],F:0.6%,M:0.3%,n:954  
	946	Complete BUSCOs (C)  
	922	Complete and single-copy BUSCOs (S)  
	24	Complete and duplicated BUSCOs (D)  
	6	Fragmented BUSCOs (F)  
	2	Missing BUSCOs (M)  
	954	Total BUSCO groups searched  

#### C. desquamator  

  C:99.3% [S:97.7%,D:1.6%],F:0.5%,M:0.2%,n:954  
	947	Complete BUSCOs (C)  
	932	Complete and single-copy BUSCOs (S)  
	15	Complete and duplicated BUSCOs (D)  
	5	Fragmented BUSCOs (F). 
	2	Missing BUSCOs (M)  
	954	Total BUSCO groups searched  

#### C. brontotheroides  

	C:99.3%[S:95.7%,D:3.6%],F:0.5%,M:0.2%,n:954  
	947	Complete BUSCOs (C)  
	913	Complete and single-copy BUSCOs (S)  
	34	Complete and duplicated BUSCOs (D)  
	5	Fragmented BUSCOs (F)  
	2	Missing BUSCOs (M)  
	954	Total BUSCO groups searched  



		Kat
		Dotplots  

## Annotation{-}  

	What we found:
		How many genes
		Quality  
		
##dn/ds{-}


-We are not doing phased haplotypes

-Get this stuff into genbank at some point
-We should not do the reproductive genes
